In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv("ratings.tsv", sep="\t")

print(df.shape)
print(df.columns.tolist())
df.head()

(15, 5)
['restaurant', 'food', 'ambience', 'service', 'rating']

   restaurant  food  ambience  service  rating
0           1    85        82       89      78
1           2    80        90       80      85
2           3    83        86       83      85
3           4    70        96       75      72
4           5    68        80       78      75

In [2]:
X = df[["ambience", "food", "service"]]
y = df["rating"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

print("Test R² score:", model.score(X_test, y_test))
print("Intercept:", model.intercept_)

Test R² score: 0.5754173218285624
Intercept: -17.214438121026163

In [3]:
coefficients = pd.DataFrame({
    "Factor": X.columns,
    "Coefficient": model.coef_
})

coefficients = coefficients.sort_values(
    "Coefficient", ascending=False
).reset_index(drop=True)

coefficients

     Factor  Coefficient
0      food     0.956768
1   service     0.203808
2  ambience     0.074014

So from my results, I found that food had the highest coefficient at around 0.96, followed by service at 0.20 and ambience at 0.07. So, if I were to run a restaurant that was struggling with its overall rating, first things first, I would focus on improving the food as it would have the strongest relationship with the overall rating. That being said, that doesn't necessarily mean improving the food alone would guarantee better ratings.

GitHub Repository

https://github.com/leonhong2007/cs82a-portfolio/tree/main/module7